modLoader="javafml"
loaderVersion="${fmlrange}"
license="MIT"
issueTrackerURL="https://github.com/FlansMods/FlansModReloaded/labels/basicparts"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
    modId="flansbasicparts"
    version="${flansbasicpartsversion}"
    displayName="Basic Parts - A Flan's Mod Content Pack"
    logoFile="flansbasicparts.png"
    credits="jamioflan"
    authors="jamioflan"
    description='''
    An essential pack for the discerning crafter of Flan's Mod tech. Gain access to a wide variety of parts, from barrels and stocks to engines and armour plating.
    Each part type has between 3 and 10 options, each made of a different material.

    There are also a wide range of munitions, varying in size (pistol rounds to artillery shells) and in effects (armour piercing, explosive or incendiary for example).

    [Coming Soon]
    Materials will provide stat modifiers and abilities to the weapons and vehicles you create
    '''
[[dependencies.flansbasicparts]]
    modId="flansmod"
    mandatory=true
    versionRange="${flansmodversionrange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.flansbasicparts]]
    modId="forge"
    mandatory=true
    versionRange="${forgeversionrange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.flansbasicparts]]
    modId="minecraft"
    mandatory=true
    versionRange="${mcversionrange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.flansbasicparts]]
    modId="jei"
    mandatory=false
    versionRange="${jeiversionrange}"
    ordering="NONE"
    side="CLIENT"